image:
  repository: positionpal/location-service
  tag: 5.5.0@sha256:c3d333c0c08bf738c06459170acc612982917e8d565aa3271a72ff8081a65632
  pullPolicy: IfNotPresent

serviceName: locservice
replicaNumber: 2
requiredContactPointNr: 2

managementPort: 8558
httpPort: 8080
grpcPort: 5052

mapboxApi: ""

akkaLicenseKey: ""

resources:
  limits:
    cpu: "1"
    memory: "512Mi"
  requests:
    cpu: "0.5"
    memory: "256Mi"

# Configure the connection information for the rabbtimq service
rabbitmq:
  username: ""
  password: ""
  namespace: ""
  serviceName: ""
  virtualHost: /
  port: 5672

# Configure the connection information for the cassandra service
cassandra:

  image:
    debug: true
 
  dbUser:
    user: admin
    password: password

  replicaCount: 2
  initDBConfigMap: script-db-configmap
