apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "location-service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.config.servicename }}
  ports:
    - protocol: TCP
      port: {{ .Values.config.httpPort }}
      targetPort: {{ .Values.config.httpPort }}
      name: http
    - protocol: TCP
      port: {{ .Values.config.grpcPort }}
      targetPort: {{ .Values.config.grpcPort }}
      name: grpc
  type: ClusterIP